name: Documentation

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/NOTICE'
      - '**/NOTICE.md'
      - '**/CODE_OF_CONDUCT.md'
      - '**/CONTRIBUTING.md'
      - '**/SECURITY.md'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
      repository-projects: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Checkout external template repository
        uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        with:
          repository: HARMAN-Automotive/CSP-Documentation
          path: CSP-Documentation
          token: ${{ secrets.REPO_TOKEN }}

      - name: Check files in the working directory
        run: |
          pwd
          ls

      - name: Build with Maven
        run: mvn -DskipTests=true cyclonedx:makeAggregateBom -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Archive BOM
        run: cp ${{ github.workspace }}/sbom/bom.xml ./bom.xml

      - name: Resolve repository in NOTICE template
        run: |
          cp ./CSP-Documentation/scripts/notice-generator.py ./notice-generator.py
          cp ./CSP-Documentation/template/NOTICE.template.md ./NOTICE.template
          cp ./CSP-Documentation/template/CODE_OF_CONDUCT.template.md ./CODE_OF_CONDUCT.md
          cp ./CSP-Documentation/template/SECURITY.template.md ./SECURITY.md
          cp ./CSP-Documentation/template/CONTRIBUTING.template.md ./CONTRIBUTING.md
          sed -i "s|{{repository}}|${{ github.repository }}|g" ./NOTICE.template
          sed -i "s|{{repository}}|${{ github.repository }}|g" ./CONTRIBUTING.md

      - name: Allow notice script to be executed
        run: chmod +x ./notice-generator.py

      - name: Execute script
        run: python ./notice-generator.py

      - name: Commit NOTICE
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add NOTICE.md CODE_OF_CONDUCT.md CONTRIBUTING.md SECURITY.md
          git diff-index --quiet HEAD || git commit -am "Generate Documentation"
          git push

      
